name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  python-black:
    name: üêç black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install --upgrade pip && pip install black==24.10.0
      - run: black . --check

  python-flake8:
    name: üêç flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install --upgrade pip && pip install flake8
      - run: flake8

  python-mypy:
    name: üêç mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install --upgrade pip && pip install mypy==1.10.1
      - name: Install uv and sync deps
        run: |
          python -m pip install uv
          uv sync --no-install-project
      - run: mypy .

  cargo-fmt:
    name: ü¶Ä cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.92.0
          override: true
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  cargo-clippy:
    name: ü¶Ä cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.92.0
          override: true
      - run: rustup component add clippy
      - run: cargo clippy --locked --all-targets -- --deny warnings
